testOnSteadyState <- function(treatmt, nameSimIndiv, CNOlist, model, timeMaxi) {

  nameFolder <- paste(nameSimIndiv,treatmt,sep="_")
  nameFile <- paste(nameFolder, "_probtraj_table.csv", sep="")
  #### File generated by a MaBoSS simulation
  dataMB <- read.table(paste(nameFolder,nameFile,sep="/"), header = TRUE)
    
  ### Reduction of the data frame
  dataMB <- dataMB[,str_detect(colnames(dataMB), "^[Prob|Time]")]
  colnames(dataMB) <- str_replace(colnames(dataMB), "^Prob.", "")
  names <- colnames(dataMB)
    
  ### List with indices of each node
  species <- model$namesSpecies
  indexRO <- list()
  for (node in species){
    indexRO[[node]] <- c()
      
    for (aTransState in names){
      if ((str_detect(aTransState, node)==TRUE)){
        indexRO[[node]] <- c(indexRO[[node]], which(names==aTransState))
      }
    }
  }
    
  ### sum of the probabilites for each time tick
  qtty <- c()
  #cmpValues <- c()
  slopeValues <- c()
  rseValues <- c()
  for(node in species) {
    indices <- indexRO[[node]]
    if(is.null(dim(dataMB[,indices])) == TRUE){
      qtty[[node]] <- dataMB[,indices]
    } else {
      qtty[[node]] <- apply(dataMB[,indices], 1, sum)
    }
    
    #####################
    ### Standard Deviation
    #lastValues <- qtty[[node]][(length(qtty[[node]])-19):(length(qtty[[node]]))]
    #sdLV <- sd(lastValues)
    #cmpValues <- c(cmpValues, sdLV)
    
    #####################
    ### Comparison of 2 values
    #cmpValues <- c(cmpValues, abs(qtty[[node]][length(qtty[[node]])-9] - qtty[[node]][length(qtty[[node]])]))
    
    #####################
    ### Comparison of the last values
    #totDiff <- 0
    #for (i in 1:9){
    #  totDiff <- totDiff + abs(qtty[[node]][length(qtty[[node]])] - qtty[[node]][length(qtty[[node]])-i])
    #}
    #cmpValues <- c(cmpValues, totDiff)
    #print(cmpValues)
      
    #####################
    ### Slope and RSE of linear Regression
    # 1) linear regression on the last values
    time <- dataMB[(dim(dataMB)[1]-19):dim(dataMB)[1],which(colnames(dataMB) == "Time")]
    regLin <- as.vector(lm(qtty[[node]][(length(qtty[[node]])-19):(length(qtty[[node]]))] ~ 
                   time))
      
    # 2) get the slope
    slopeValues <- c(slopeValues,regLin$coefficient[2])
    rseValues <- c(rseValues, summary(regLin)$sigma)
    
    #####################
    ### Get the pvalue of the linear regression
    #print(qtty[[node]][(length(qtty[[node]])-19):(length(qtty[[node]]))])
    # 1) linear regression on the last values
    #time <- dataMB[(dim(dataMB)[1]-19):dim(dataMB)[1],which(colnames(dataMB) == "Time")]
    #regLin <- lm(qtty[[node]][(length(qtty[[node]])-19):(length(qtty[[node]]))] ~ 
    #               time)
    
    # 2) get the slope
    #cmpValues <- c(cmpValues,summary(regLin)$coefficients[[8]])

  }
    
    
    ### plot the data
    #myPath <- getwd()
    #timeSeq <- dataMB[,which(colnames(dataMB) == "Time")]
    #pdf(paste(myPath,"/allCond/",nameFolder, "_", timeMaxi,".pdf", sep=""))
    #par(mfrow=c(1,1))
    #vecCol <- rainbow(length(species)-1)
    #plot(timeSeq, unlist(qtty[[1]]), type="l", col=1, ylim = c(0,1), main = paste(nameFolder,"_", timeMaxi, sep=""))
    #for (i in 2:length(species)){
    #  spec <- species[i]
    #  lines(timeSeq, unlist(qtty[[spec]]), col=vecCol[i-1])
    #}
    #legend("right", legend = names(qtty), col = c(1,vecCol), lwd = 1, title = )
    #dev.off()
    
    ### plot the end
    #pdf(paste(myPath,"/allCond/end_",nameFolder, "_", timeMaxi,".pdf", sep=""))
    #plot(timeSeq, unlist(qtty[[1]]), type="l", xlim = c(timeMaxi-1,timeMaxi), ylim = c(0,1), col=1, main = paste(nameFolder,"_", timeMaxi, sep=""))
    #axis(side = 1, at = seq(timeMaxi-1,timeMaxi, by = 0.1))
    #axis(side = 2, at = seq(0,1, by = 0.1))
    #for (i in 2:length(species)){
    #  spec <- species[i]
    #  lines(timeSeq, unlist(qtty[[spec]]), col=vecCol[i-1])
    #}
    #legend("right", legend = names(qtty), col = c(1,vecCol), lwd = 1, xpd = NA)
    #dev.off()
    
    
    
    
    
    #####################
    ### Test when using comparison
    #print(cmpValues)
    #i <- 1
    #addTime <- FALSE
    #while(i <= length(cmpValues) && addTime == FALSE){
    #  if (cmpValues[i] > 0.001 || cmpValues[i] < -0.001) {
    #    addTime <- TRUE
    #  }
    #  i <- i + 1
    #}
    #print(i-1)
    
    #####################
    ### t.test on the Entropy
    #for(node in colnames(CNOlist@signals)){
    #  evalSS <- t.test(qtty[[node]][ (length(qtty[[node]])-100) : (length(qtty[[node]])-41) ],
    #                   qtty[[node]][ (length(qtty[[node]])-40) : (length(qtty[[node]]))],
    #                   alternative = "two.sided"
    #  )
    #  if (evalSS$p.value < 0.05) {
    #    addTime <- TRUE
    #  }
    #}
    
    #####################
    ### pvalue of the linear regression
    #i <- 1
    #addTime <- FALSE
    #cmpValues <- na.omit(cmpValues)
    #while(i <= length(cmpValues) && addTime == FALSE){
    #  if (cmpValues[i] < 0.05) {
    #    addTime <- TRUE
    #  }
    #  i <- i + 1
    #}
    
    #####################
    ### slope and rse of the linear regression
    i <- 1
    addTime <- FALSE
    #slopeValues <- na.omit(slopeValues)
    while(i <= length(slopeValues) && addTime == FALSE){
      #print(paste("the slope : ", slopeValues[i], " and the RSE : ", rseValues[i], sep = ""))
      if ((slopeValues[i] > 0.0001 || rseValues[i] > 0.0001) && (timeMaxi < max(CNOlist@timepoints)*5)) {
        addTime <- TRUE
      }
      i <- i + 1
    }
  
  
  ### plot the data
  densityNodesMbss <- function(dataMB, nameFolder, timeMaxi, species, qtty) {
    myPath <- getwd()
    timeSeq <- dataMB[,which(colnames(dataMB) == "Time")]
    pdf(paste(myPath,"/probPlots/",nameFolder, "_", timeMaxi,".pdf", sep=""))
    par(mfrow=c(1,1))
    vecCol <- rainbow(length(species)-1)
    plot(timeSeq, unlist(qtty[[1]]), type="l", col=1, ylim = c(0,1), main = paste(nameFolder,"_", timeMaxi, sep=""))
    for (i in 2:length(species)){
      spec <- species[i]
      lines(timeSeq, unlist(qtty[[spec]]), col=vecCol[i-1])
    }
    legend("right", legend = names(qtty), col = c(1,vecCol), lwd = 1, xpd = NA)
    dev.off()
  }
  #densityNodesMbss(dataMB, nameFolder, timeMaxi, species, qtty)
  
  print(addTime)
  
  if (addTime == TRUE) {
    print("Need more time to reach the steady state :")
    print("Test realised on the slope and RSE of the linear regression")
    timeMaxi <- timeMaxi+max(CNOlist@timepoints)
  }
  return(timeMaxi)
}